const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const csv = require('csv-parser');
const User = require('./models/User');
const Category = require('./models/Category');
const Product = require('./models/Product');

dotenv.config();

// ── CSV Import Helper ───────────────────────────────────────────────────────
// Reads inventory.csv from the server root and returns parsed rows.
// Expected columns: ProductName, Description, Category, ImageUrl, Tags,
//                   Material, Frame, Size, Color, Price, ComparePrice, Stock
// Multiple rows with the same ProductName are grouped as variations.
const importCSVProducts = (filePath) => {
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(filePath)) {
      return resolve(null);
    }
    const results = [];
    fs.createReadStream(filePath)
      .pipe(csv())
      .on('data', (data) => results.push(data))
      .on('end', () => resolve(results))
      .on('error', (error) => reject(error));
  });
};

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected for seeding...');

    // ═══════════════════════════════════════════
    //         CRITICAL SECURITY GATEKEEPER
    // ═══════════════════════════════════════════
    // Only block when NODE_ENV is explicitly 'production'.
    // The previous URI-based check (MONGO_URI.includes('cluster')) was too
    // aggressive — it also blocked staging Atlas URIs, making it impossible
    // to repair broken seed data on staging without a --force bypass.
    // Set NODE_ENV=production in the Render production service and
    // NODE_ENV=staging (or omit it) in the Render staging service.
    if (process.env.NODE_ENV === 'production') {
      console.error('\n  AUDIT BLOCK: Destructive data injection scripts cannot be executed on the live Production Database cluster!\n');
      process.exit(1);
    }

    // Only wipe data if explicitly running a local system reset via --clear flag
    if (process.argv.includes('--clear')) {
      console.log('  Clearing existing local collection data...');
      await User.deleteMany({});
      await Category.deleteMany({});
      await Product.deleteMany({});
    } else {
      console.log('  Skipping collection clear (pass --clear to wipe first)');
    }

    // ═══════════════════════════════════════════
    //         ADMIN CREDENTIAL GATEKEEPER
    // ═══════════════════════════════════════════
    // ADMIN_EMAIL and ADMIN_PASSWORD must be set explicitly in .env or Render
    // dashboard. Falling back to hardcoded defaults creates an insecure
    // gateway admin with a predictable email address.
    if (!process.env.ADMIN_EMAIL || !process.env.ADMIN_PASSWORD) {
      console.error('\n  AUDIT BLOCK: ADMIN_EMAIL and ADMIN_PASSWORD must be set in .env before seeding.');
      console.error('  Set them in your .env file or Render dashboard, then re-run.\n');
      process.exit(1);
    }

    const adminEmail = process.env.ADMIN_EMAIL;
    const adminPassword = process.env.ADMIN_PASSWORD;

    const existingAdmin = await User.findOne({ email: adminEmail });
    if (!existingAdmin) {
      await User.create({
        name: 'Admin',
        email: adminEmail,
        password: adminPassword,
        role: 'admin',
        phone: '+91 9876543210'
      });
      console.log(`Admin user created: ${adminEmail}`);
    } else {
      console.log('Admin user already exists, skipping');
    }

    // Demo user is optional — only create if DEMO_PASSWORD is provided
    if (process.env.DEMO_PASSWORD) {
      const existingDemo = await User.findOne({ email: 'user@gpsfdk.com' });
      if (!existingDemo) {
        await User.create({
          name: 'Demo User',
          email: 'user@gpsfdk.com',
          password: process.env.DEMO_PASSWORD,
          role: 'user',
          phone: '+91 9876543211'
        });
        console.log('Demo user created');
      } else {
        console.log('Demo user already exists, skipping');
      }
    }

    // Create categories (upsert to avoid duplicates)
    // NOTE: `slug` is also auto-generated by the pre('save') hook in Category.js,
    // but we set it explicitly here as defense-in-depth. The frontend (Navbar,
    // CategoryHighlights, HomePage, ProductPage, etc.) hard-codes these exact
    // slug strings — if the slug ever drifts, every `/api/categories/:slug`
    // lookup 404s and the category page silently breaks.
    let wallCanvas = await Category.findOne({ slug: 'wall-canvas' });
    if (!wallCanvas) {
      wallCanvas = await Category.create({
        name: 'Wall Canvas',
        slug: 'wall-canvas',
        description: 'Premium wall canvases for your home & office',
        image: { url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800', public_id: '' }
      });
      console.log('Wall Canvas category created');
    }

    let houseNameplates = await Category.findOne({ slug: 'house-nameplates' });
    if (!houseNameplates) {
      houseNameplates = await Category.create({
        name: 'House Nameplates',
        slug: 'house-nameplates',
        description: 'Custom luxury house nameplates',
        image: { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800', public_id: '' }
      });
      console.log('House Nameplates category created');
    }

    console.log('Categories ready');

    // ── Try CSV import first, fall back to hardcoded seed data ───────────
    const csvPath = require('path').join(__dirname, 'inventory.csv');
    const csvRows = await importCSVProducts(csvPath);

    if (csvRows && csvRows.length > 0) {
      console.log(`\n  Importing ${csvRows.length} rows from inventory.csv...`);

      const categoryMap = {
        'wall canvas': wallCanvas._id,
        'canvas': wallCanvas._id,
        'house nameplates': houseNameplates._id,
        'nameplates': houseNameplates._id,
        'nameplate': houseNameplates._id,
      };

      // Group rows by ProductName so multiple rows become variations
      const grouped = {};
      for (const row of csvRows) {
        const name = (row.ProductName || '').trim();
        if (!name) continue;
        if (!grouped[name]) grouped[name] = { rows: [], first: row };
        grouped[name].rows.push(row);
      }

      let imported = 0;
      for (const [name, group] of Object.entries(grouped)) {
        const first = group.first;
        const catKey = (first.Category || '').trim().toLowerCase();
        const categoryId = categoryMap[catKey] || wallCanvas._id;

        const variations = group.rows.map(row => ({
          material: (row.Material || '').trim(),
          frame: (row.Frame || '').trim(),
          size: (row.Size || '').trim(),
          color: (row.Color || '').trim(),
          price: Number(row.Price) || 0,
          comparePrice: Number(row.ComparePrice) || 0,
          stock: Number(row.Stock) || 100,
        })).filter(v => v.size && v.price > 0);

        if (variations.length === 0) {
          console.log(`  Skipping "${name}" — no valid variations`);
          continue;
        }

        const tags = (first.Tags || '').split(',').map(t => t.trim()).filter(Boolean);
        const isNameplate = catKey.includes('nameplate');

        await Product.create({
          name,
          description: (first.Description || '').trim(),
          shortDescription: (first.Description || '').substring(0, 80).trim(),
          category: categoryId,
          images: [{ url: (first.ImageUrl || '').trim(), public_id: '', alt: name }],
          variations,
          customizable: isNameplate,
          customizationLabel: isNameplate ? 'Enter your family name' : undefined,
          tags,
        });
        imported++;
      }

      console.log(`  CSV inventory import complete: ${imported} products created`);

    } else {
      console.log('\n  No inventory.csv found — using built-in seed data...');

      // ── Wall Canvas products (hardcoded fallback) ─────────────────────
      const canvasProducts = [
        { name: 'The Wolf of Wall Street', desc: 'Iconic cinematic art for the ambitious soul. A bold statement piece for your workspace.', tags: ['cinema', 'motivation', 'office'] },
        { name: 'The Social Outcast', desc: 'Abstract rebellion meets modern art. Perfect for those who dare to stand apart.', tags: ['abstract', 'modern', 'living-room'] },
        { name: 'Noir Petal Sweep', desc: 'Dark botanical elegance captured in sweeping strokes of midnight and gold.', tags: ['botanical', 'dark', 'bedroom'] },
        { name: 'Azure Gaze', desc: 'Mesmerizing blue tones that evoke the calm of the endless ocean.', tags: ['blue', 'calm', 'minimal'] },
        { name: 'Dreaming in Colors', desc: 'A kaleidoscope of imagination brought to canvas. Vibrant and utterly captivating.', tags: ['colorful', 'vibrant', 'living-room'] },
        { name: 'Volcanic Core', desc: 'Raw energy captured in molten hues. A piece that commands attention.', tags: ['bold', 'red', 'office'] },
        { name: 'Obsidian Ember', desc: 'Deep charcoal meets smouldering amber in this sophisticated composition.', tags: ['dark', 'sophisticated', 'office'] },
        { name: 'The Noir Executive', desc: 'Monochrome elegance for the modern executive. Timeless confidence on canvas.', tags: ['monochrome', 'executive', 'office'] },
        { name: 'The Concrete Jungle', desc: 'Urban architecture meets artistic vision. The city as you have never seen it.', tags: ['urban', 'architecture', 'modern'] },
        { name: 'Neon Nostalgia', desc: 'Retro-futuristic vibes painted in electric neon. A conversation starter.', tags: ['neon', 'retro', 'living-room'] },
        { name: 'The Gilded Bloom', desc: 'Luxurious golden florals on a rich dark background. Pure opulence for your walls.', tags: ['floral', 'gold', 'luxury'] },
        { name: 'Celestial Frontier', desc: 'Journey through the cosmos with this stunning interstellar art piece.', tags: ['space', 'cosmic', 'bedroom'] },
        { name: 'The Dapper Predator', desc: 'Raw power meets refined elegance. A bold predator rendered in striking monochrome strokes.', tags: ['animal', 'bold', 'monochrome', 'living-room'] },
      ];

      const canvasVariations = [
        { material: 'Poster', frame: 'Soft Board', size: 'A4', price: 99, comparePrice: 199 },
        { material: 'Poster', frame: 'Sticker', size: 'A3', price: 149, comparePrice: 299 },
        { material: 'Poster', frame: 'Paper', size: '12x18', price: 199, comparePrice: 399 },
        { material: 'Canvas', frame: 'Rolled', size: '18x24', price: 999, comparePrice: 1999 },
        { material: 'Canvas', frame: 'Rolled', size: '24x36', price: 1999, comparePrice: 3999 },
        { material: 'Canvas', frame: 'Stretched', size: '24x36', price: 3499, comparePrice: 5999 },
        { material: 'Canvas', frame: 'Stretched', size: '30x48', price: 4999, comparePrice: 6999 },
        { material: 'Canvas', frame: 'Stretched', size: '36x60', price: 7999, comparePrice: 9999 },
      ];

      const canvasImages = [
        'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=800',
        'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
        'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800',
        'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800',
        'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800',
        'https://images.unsplash.com/photo-1574182245530-967d9b3831af?w=800',
        'https://images.unsplash.com/photo-1577720580479-7d839d829c73?w=800',
        'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=800',
        'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800',
        'https://images.unsplash.com/photo-1482160549825-59d1b23cb208?w=800',
        'https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?w=800',
        'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800',
        'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800',
      ];

      // Find-then-fix approach: create missing products, repair empty-variation
      // products, skip products that already have valid variations. This makes
      // the seed safe to re-run without --clear and without any data loss.
      let canvasCreated = 0, canvasRepaired = 0;
      for (let i = 0; i < canvasProducts.length; i++) {
        const existing = await Product.findOne({ name: canvasProducts[i].name });
        if (!existing) {
          await Product.create({
            name: canvasProducts[i].name,
            description: canvasProducts[i].desc,
            shortDescription: canvasProducts[i].desc.substring(0, 80),
            category: wallCanvas._id,
            images: [{ url: canvasImages[i], public_id: '', alt: canvasProducts[i].name }],
            variations: canvasVariations,
            featured: i < 6,
            isMasonry: i >= 4 && i < 10,
            tags: canvasProducts[i].tags,
          });
          canvasCreated++;
        } else if (!existing.variations || existing.variations.length === 0) {
          existing.variations = canvasVariations;
          await existing.save();
          console.log(`  Repaired empty variations for: ${canvasProducts[i].name}`);
          canvasRepaired++;
        }
      }
      console.log(`Wall Canvas products: ${canvasCreated} created, ${canvasRepaired} repaired, ${canvasProducts.length - canvasCreated - canvasRepaired} already healthy`);

      // ── House Nameplate products (hardcoded fallback) ─────────────────
      const nameplateProducts = [
        { name: 'Lord Ganesha', desc: 'Traditional Lord Ganesha design with modern metallic finish. Brings blessings to your doorstep.', colors: ['Black & Gold', 'Black & Silver'] },
        { name: 'Modern House', desc: 'Sleek geometric lines with a contemporary feel. Perfect for modern homes.', colors: ['Black & Gold', 'Black & Silver'] },
        { name: 'Silver Ganesha', desc: 'Elegant silver-toned Ganesha motif. A spiritual welcome to your abode.', colors: ['Silver & White', 'Silver & Black'] },
        { name: 'Sunehra Naam', desc: 'Golden lettering on premium acrylic. Your name in pure luxury.', colors: ['Gold & Black', 'Gold & Maroon'] },
        { name: 'Just Right', desc: 'Minimalist perfection. Clean lines, bold presence.', colors: ['Black & Gold', 'White & Gold'] },
        { name: 'House Of Gold', desc: 'Full gold treatment for the ultimate luxury statement at your entrance.', colors: ['Gold & Black', 'Gold & Brown'] },
        { name: 'Silver Circle', desc: 'Circular design with silver accents. Modern meets elegance.', colors: ['Silver & Black', 'Silver & White'] },
        { name: 'Trishula', desc: 'Sacred trident design symbolizing power and protection.', colors: ['Black & Gold', 'Black & Silver'] },
      ];

      const nameplateImages = [
        'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800',
        'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800',
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
        'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
        'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
      ];

      let npCreated = 0, npRepaired = 0;
      for (let i = 0; i < nameplateProducts.length; i++) {
        const np = nameplateProducts[i];
        const variations = [];
        for (const color of np.colors) {
          variations.push({ color, size: '15 inch', price: 1999, comparePrice: 2999, stock: 50 });
          variations.push({ color, size: '18 inch', price: 2499, comparePrice: 3499, stock: 50 });
        }
        const existing = await Product.findOne({ name: np.name });
        if (!existing) {
          await Product.create({
            name: np.name,
            description: np.desc,
            shortDescription: np.desc.substring(0, 80),
            category: houseNameplates._id,
            images: [{ url: nameplateImages[i], public_id: '', alt: np.name }],
            variations,
            customizable: true,
            customizationLabel: 'Enter your family name',
            featured: i < 4,
            isMasonry: i >= 2 && i < 6,
            tags: ['nameplate', 'custom', 'home-decor'],
          });
          npCreated++;
        } else if (!existing.variations || existing.variations.length === 0) {
          existing.variations = variations;
          await existing.save();
          console.log(`  Repaired empty variations for: ${np.name}`);
          npRepaired++;
        }
      }
      console.log(`House Nameplate products: ${npCreated} created, ${npRepaired} repaired, ${nameplateProducts.length - npCreated - npRepaired} already healthy`);
    }

    console.log('\nDatabase seeded successfully!');
    console.log('Admin:', process.env.ADMIN_EMAIL || 'admin@gpsfdk.com', '/', process.env.ADMIN_PASSWORD ? '(from env)' : adminPassword);
    console.log('User:  user@gpsfdk.com /', process.env.DEMO_PASSWORD ? '(from env)' : demoPassword);
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
};

seed();
